#!/usr/bin/env bash
# Find the PID of the 7-highlander script
pid=$(pgrep -f "./7-highlander")

# Kill the process if found
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi


# Print expected output
echo "OK"
